name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        IMAGE_TAG=python-test:$(date +%s)
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        docker build . --file Dockerfile --tag $IMAGE_TAG
    - name: Run 
      run: docker run -d --name python-test -v ${{ github.workspace }}/allure-results:/app/allure-results ${{ env.IMAGE_TAG }}
    
    - name: Wait for container to finish
      run: |
        CONTAINER_ID=$(docker ps -q --filter "name=python-test")
        while [ -n "$CONTAINER_ID" ]; do
          sleep 5
          CONTAINER_ID=$(docker ps -q --filter "name=python-test")
        done

    - name: Get logs from the Docker container
      run: docker logs python-test

    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
